"""Controlled taxonomy vocabularies for Bhāva Library curation."""

from __future__ import annotations

TAXONOMY: dict[str, list[str]] = {
    "content-form": [
        "comic",
        "illustrated-storybook",
        "prose-story",
        "curriculum",
        "syllabus",
        "lesson-plan",
        "teacher-guide",
        "parent-guide",
        "student-workbook",
        "activity-book",
        "worksheet",
        "coloring-page",
        "coloring-book",
        "crossword",
        "word-search",
        "maze",
        "connect-the-dots",
        "matching",
        "sequencing",
        "cut-and-paste",
        "craft",
        "poster",
        "flashcard",
        "quiz",
        "assessment",
        "game",
        "drama-script",
        "puppet-script",
        "song-lyrics",
        "prayer",
        "sloka-card",
        "pronunciation-guide",
        "reference-book",
        "article",
        "presentation",
        "audio-story",
        "lecture-audio",
        "kirtan",
        "bhajan",
        "music",
        "prayer-audio",
        "pronunciation-audio",
        "drama-audio",
        "curriculum-audio",
        "archive-bundle",
        "unknown",
    ],
    "audience": [
        "ages-3-5",
        "ages-4-7",
        "ages-5-7",
        "ages-6-8",
        "ages-7-9",
        "ages-8-11",
        "ages-9-12",
        "ages-9-13",
        "ages-11-14",
        "youth",
        "adult",
        "parent",
        "teacher",
        "mixed-family",
        "unknown",
    ],
    "program-use": [
        "sunday-school",
        "bal-gopal",
        "damodara-class",
        "gopinath-class",
        "gurukula",
        "homeschool",
        "family-bhakti",
        "festival-program",
        "temple-camp",
        "youth-program",
        "teacher-training",
        "general-reference",
    ],
    "classroom-function": [
        "opening-activity",
        "storytelling",
        "guided-reading",
        "discussion",
        "memorization",
        "art",
        "craft",
        "group-game",
        "individual-work",
        "assessment",
        "homework",
        "parent-extension",
        "teacher-preparation",
        "performance",
        "festival-display",
        "take-home",
        "reward",
    ],
    "topic": [
        "krishna",
        "balarama",
        "radha",
        "caitanya-mahaprabhu",
        "nityananda",
        "panca-tattva",
        "srila-prabhupada",
        "gaudiya-acaryas",
        "great-devotees",
        "bhagavad-gita",
        "srimad-bhagavatam",
        "krishna-book",
        "ramayana",
        "mahabharata",
        "deity-worship",
        "vaisnava-etiquette",
        "holy-name",
        "japa",
        "kirtan",
        "prasada",
        "cow-protection",
        "holy-places",
        "festivals",
        "sanskrit",
        "philosophy",
        "values",
        "devotional-practice",
        "history",
        "comparative-religion",
        "teacher-development",
    ],
    "person": [
        "krishna",
        "balarama",
        "radha",
        "caitanya-mahaprabhu",
        "nityananda",
        "srila-prabhupada",
    ],
    "festival": [
        "janmastami",
        "radhastami",
        "gaura-purnima",
        "nrsimha-caturdasi",
        "rama-navami",
        "govardhana-puja",
        "dipavali",
        "damodara-month",
        "ratha-yatra",
        "appearance-day",
        "disappearance-day",
        "ekadasi",
        "other",
    ],
    "scripture": [
        "bhagavad-gita",
        "srimad-bhagavatam-canto-chapter",
        "krishna-book-chapter",
        "caitanya-caritamrta",
        "nectar-of-devotion",
        "nectar-of-instruction",
        "isopanisad",
        "ramayana",
        "mahabharata",
        "vaisnava-song",
        "prabhupada-letter",
        "prabhupada-lecture",
        "biography",
        "secondary-source",
        "unknown",
    ],
    "language": [
        "english",
        "hindi",
        "bengali",
        "sanskrit",
        "spanish",
        "mixed",
        "unknown",
    ],
    "production-opportunity": [
        "no-action",
        "useful-reference",
        "curriculum-gap",
        "original-comic-candidate",
        "original-story-candidate",
        "printable-candidate",
        "activity-candidate",
        "teacher-guide-candidate",
        "audio-remaster-candidate",
        "translation-candidate",
        "festival-pack-candidate",
        "sunday-school-candidate",
        "needs-source-verification",
        "do-not-use",
    ],
    "reference-boundary": [
        "facts-only",
        "topic-inspiration",
        "pedagogical-inspiration",
        "structure-review-only",
        "visual-quality-benchmark",
        "private-reference-only",
        "restricted-do-not-process",
        "public-domain-verified",
        "bhava-original",
    ],
}

RULE_VERSION = "rules-v2.0"


def term_id(dimension: str, value: str) -> str:
    return f"{dimension}:{value}"
